### ISSUE TITLE
Where is Kosovo?

### ISSUE THREAD

**Issue by Tigrov** [MenaraSolutions/geographer-data#1]
You have states for Kosovo
https://github.com/MenaraSolutions/geographer-data/blob/master/resources/states/XK.json

Why the country is missed in the list?
https://github.com/MenaraSolutions/geographer-data/blob/master/resources/countries.json

**Comment by dusterio** [comment]
Kosovo doesn't have an ISO code and by default Geographer uses ISO standard for divisions.

According to wikipedia:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
The code XK is being used by the European Commission,[20] Switzerland,[21] the Deutsche Bundesbank,[22] SWIFT,[23] and other organizations as a temporary country code for Kosovo.[24]

I tried to make Geographer 100% compliant with ISO so I removed/edited all states. GeoNames database was _very_ inconsistent and often mixed FIPS, fake FIPS, ISO and GeoNames all together.

Having said that, Geographer supports other standards and will keep adding/improving them so Kosovo will probably appear in one of them.

I'm also considering adding something like 'defacto' or 'including disputed' flag/standard.
