### ISSUE TITLE
Wrong geoname code for MC-SR

### ISSUE THREAD

**Issue by Tigrov** [MenaraSolutions/geographer-data#2]
https://github.com/MenaraSolutions/geographer-data/blob/master/resources/states/MC.json

Geoname code for Saint Roman is 3225774
http://www.geonames.org/3225774/saint-roman.html

**Comment by dusterio** [comment]
Actually, as far as I can see - it should be removed completely. GeoNames only got one division for Monaco:
http://download.geonames.org/export/dump/admin1CodesASCII.txt

Which is Commune de Monaco. And according to Italian wikipedia, Saint Roman is a part of Commune de Monaco, it doesn't have its own status
