### ISSUE TITLE
invalid geonames code

### ISSUE THREAD

**Issue by Xmk** [MenaraSolutions/geographer-data#3]
**City San Antonio on Philippines**
have [1690315](http://www.geonames.org/1690315),
true [1690313](http://www.geonames.org/1690313/) or [1690314](http://www.geonames.org/1690314/)

**Tonawanda on United States, New York**
have [7259084](http://www.geonames.org/7259084),
true [5141175](http://www.geonames.org/5141175)

**Comment by dusterio** [comment]
Thanks! Fixed both
It seems Geonames changed the codes

**Comment by Xmk** [comment]
data keys don't need change? https://github.com/MenaraSolutions/geographer-data/commit/0a9b68ced5686d641a8ba184c417b1a715b4fc85#diff-951c9b31f7d2d75dac69563d0a5e81fbR522
