### ISSUE TITLE
Крым

### ISSUE THREAD

**Issue by Xmk** [MenaraSolutions/geographer-data#31]
По geonames Крым относится к России, наверное надо перенести

**Comment by dusterio** [comment]
@Xmk я хотел еще какой-то флаг добавить вроде "disputed": true/false, и поместить и в UA.json и в RU.json, чтобы была полная прозрачность. Тоже относится еще к нескольким территориям на планете - это будет повторяющийся use case

**Comment by Xmk** [comment]
@dusterio да, наверное так будет правильней.

p.s. можешь в диалог вступить https://github.com/MenaraSolutions/geographer/pull/37?
не совсем понятно как вывести список всех городов страны без метода merge для коллекций

**Comment by Maxpain177** [comment]
@Xmk что-то не вижу чтобы в geonames Крым был в России. Поделитесь ссылкой?

**Comment by Xmk** [comment]
@Maxpain177 

> наверное надо перенести

**Comment by taschan23** [comment]
Привет! Пока тишина по этому вопросу? Не хватает Крыма в РФ.
