### ISSUE TITLE
One code for two different cities

### ISSUE THREAD

**Issue by aboldyrev** [MenaraSolutions/geographer-data#6]
One code for two different cities: Rustavi(GE), Zestaponi(GE)
`"612287": {
		"ids": {
			"geonames": 612287
		},
		"long": {
			"default": "Rustavi"
		},
		"parent": 865536,
		"lat": 41.51667,
		"lng": 44.51667,
		"country": "GE",
		"population": 125103
	},
	"610864": {
		"ids": {
			"geonames": 612287
		},
		"long": {
			"default": "Zestaponi"
		},
		"parent": 865539,
		"lat": 42.11,
		"lng": 43.0525,
		"country": "GE",
		"population": 57628
	}`

**Comment by dusterio** [comment]
Thanks, fixed just now!

Apparently Geonames DB has some typos and mistakes
